/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: 58852125f1b0d2e621fc2ba295e75198)
interface __BaseEnv_CloudflareBindings {
	ADMIN_OBJECTS: R2Bucket;
	LARGE_OBJECTS: R2Bucket;
	DB: D1Database;
	ADMIN_QUEUE: Queue;
	ASSETS: Fetcher;
	ADMIN_ACCESS_ISSUER: "https://unconfigured.cloudflareaccess.invalid";
	ADMIN_ACCESS_AUDIENCE: "UNCONFIGURED_DENY_ALL";
	ADMIN_ACCESS_JWKS_URL: "https://unconfigured.cloudflareaccess.invalid/cdn-cgi/access/certs";
	ADMIN_PRINCIPALS_JSON: "[]";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_ACCESS_ISSUER" | "ADMIN_ACCESS_AUDIENCE" | "ADMIN_ACCESS_JWKS_URL" | "ADMIN_PRINCIPALS_JSON">> {}
}
