import { z } from 'zod';
import { getTableColumns } from 'drizzle-orm';
import { battleReportGenerations, battleReportGenerationCombatants, arenaRatingEvents, pvpRounds, pvpRoomChatMessages, pvpRoomHands, pvpRoomSubmissions, pvpRoomCardSnapshots, pvpRoundChoices, largeObjects } from '../db/schema/business';
import { type AdminDatabase, assertAdminBatchSucceeded } from './database';
import { executeAdminOperation, AdminOperationError, type AdminGuardedStatement } from './operations';
import { commonInput, type AdminActionContext } from './actions/core';
import { readAdminResource } from './read-models';

/** Private R2 only; keys are generated by the service and never accepted as download paths. */
export interface AdminPrivateBucket {
  put(_key:string,_body:string|ReadableStream<Uint8Array>):Promise<unknown>;
  get(_key:string):Promise<{text():Promise<string>;body:ReadableStream<Uint8Array>}|null>;
  delete(_key:string):Promise<unknown>;
}
const terminalGeneration = (alias:string) => `${alias}.status IN ('completed','aborted','failed') AND (${alias}.extra_json IS NULL OR (json_valid(${alias}.extra_json)=1 AND coalesce(json_extract(${alias}.extra_json,'$.finalizationCompleted'),1)=1))`;
const terminalRoom = (column:string) => `EXISTS (SELECT 1 FROM pvp_rooms room WHERE room.id=${column} AND room.status IN ('closed','ended') AND NOT EXISTS (SELECT 1 FROM pvp_matches active WHERE active.room_id=room.id AND active.status NOT IN ('completed','aborted','failed','cancelled')) AND NOT EXISTS (SELECT 1 FROM pvp_rounds busy WHERE busy.room_id=room.id AND busy.status NOT IN ('completed','aborted','failed','cancelled'))) `;
const terminalLinkedGeneration = (column:string) => `EXISTS (SELECT 1 FROM battle_report_generations g WHERE g.id=${column} AND ${terminalGeneration('g')}) AND NOT EXISTS (SELECT 1 FROM pvp_rounds r WHERE r.battle_generation_id=${column})`;
const definitions = {
  battle_report_generations:{table:battleReportGenerations,key:'id',safe:`${terminalGeneration('battle_report_generations')} AND NOT EXISTS (SELECT 1 FROM pvp_rounds r WHERE r.battle_generation_id=battle_report_generations.id) AND NOT EXISTS (SELECT 1 FROM arena_rating_events e WHERE e.generation_id=battle_report_generations.id) AND NOT EXISTS (SELECT 1 FROM battle_report_generation_combatants c WHERE c.generation_id=battle_report_generations.id) AND NOT EXISTS (SELECT 1 FROM large_objects o WHERE o.owner_ref_id=battle_report_generations.id)`},
  battle_report_generation_combatants:{table:battleReportGenerationCombatants,key:'id',safe:terminalLinkedGeneration('battle_report_generation_combatants.generation_id')},
  arena_rating_events:{table:arenaRatingEvents,key:'id',safe:`status IN ('applied','skipped','failed') AND ${terminalLinkedGeneration('arena_rating_events.generation_id')}`},
  pvp_rounds:{table:pvpRounds,key:'id',safe:`status IN ('completed','aborted','failed','cancelled') AND ${terminalRoom('pvp_rounds.room_id')} AND NOT EXISTS (SELECT 1 FROM pvp_round_choices c WHERE c.round_id=pvp_rounds.id)`},
  pvp_room_chat_messages:{table:pvpRoomChatMessages,key:'id',safe:terminalRoom('pvp_room_chat_messages.room_id')},
  pvp_room_hands:{table:pvpRoomHands,key:'json_array(room_id,user_id)',safe:terminalRoom('pvp_room_hands.room_id')},
  pvp_room_submissions:{table:pvpRoomSubmissions,key:'json_array(room_id,user_id)',safe:terminalRoom('pvp_room_submissions.room_id')},
  pvp_room_card_snapshots:{table:pvpRoomCardSnapshots,key:'id',safe:terminalRoom('pvp_room_card_snapshots.room_id')},
  pvp_round_choices:{table:pvpRoundChoices,key:'json_array(round_id,user_id)',safe:`EXISTS (SELECT 1 FROM pvp_rounds r WHERE r.id=pvp_round_choices.round_id AND r.status IN ('completed','aborted','failed','cancelled') AND ${terminalRoom('r.room_id')})`},
  large_objects:{table:largeObjects,key:'id',safe:`kind='battle_report_generation_output' AND NOT EXISTS (SELECT 1 FROM large_objects other WHERE other.r2_key=large_objects.r2_key AND other.id<>large_objects.id) AND ${terminalLinkedGeneration('large_objects.owner_ref_id')}`},
} as const;
export const ADMIN_CLEANUP_TARGETS=Object.keys(definitions);
type CleanupTarget=keyof typeof definitions;
const targetSchema=z.enum(ADMIN_CLEANUP_TARGETS as [CleanupTarget,...CleanupTarget[]]);
const idsSchema=z.array(z.string().min(1).max(512)).min(1).max(100).refine(ids=>new Set(ids).size===ids.length);
const previewSchema=z.object({target:targetSchema,ids:idsSchema}).strict();
const exportTargets=z.enum(['data-cards','generations']);
const jobSchema=z.discriminatedUnion('kind',[
 z.object({...commonInput,kind:z.literal('export'),target:exportTargets,ids:idsSchema}).strict(),
 z.object({...commonInput,kind:z.literal('cleanup'),target:targetSchema,ids:idsSchema,previewVersion:z.string().length(64)}).strict(),
 z.object({...commonInput,kind:z.literal('restore'),sourceJobId:z.string().uuid()}).strict(),
]);
type Scope={target:string;ids:string[];versions?:string[];sourceJobId?:string};
const digest=async(value:unknown)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)))),b=>b.toString(16).padStart(2,'0')).join('');
const columns=(target:CleanupTarget)=>Object.values(getTableColumns(definitions[target].table)).map(c=>c.name);
const eligible=(target:CleanupTarget)=>`(${definitions[target].safe}) AND julianday(created_at)<julianday('now','-30 days')`;
async function cleanupRow(db:AdminDatabase,target:CleanupTarget,id:string){
 const result=await db.prepare(`SELECT ${columns(target).join(',')} FROM ${target} WHERE ${definitions[target].key}=? AND ${eligible(target)}`).bind(id).first<Record<string,unknown>>();
 return result;
}
/** Explicit identifiers only. Preview does not write tables, audits or queues. */
export async function previewAdminCleanup(db:AdminDatabase,raw:unknown){
 const input=previewSchema.parse(raw);const versions:string[]=[];
 for(const id of input.ids){const row=await cleanupRow(db,input.target,id);if(!row)throw new AdminOperationError('ADMIN_CLEANUP_TARGET_NOT_ELIGIBLE',409);versions.push(await digest(row));}
 return {target:input.target,ids:input.ids,count:input.ids.length,retentionDays:30,previewVersion:await digest([input.target,input.ids,versions]),versions};
}
export async function createAdminJob(db:AdminDatabase,raw:unknown,context:AdminActionContext){
 const input=jobSchema.parse(raw);let scope:Scope;const capability=input.kind==='export'?'exports.read':'data.maintenance';
 const previous=await db.prepare('SELECT target_type,target_id FROM admin_operations WHERE actor_principal_id=? AND idempotency_key=?').bind(context.principalId,input.idempotencyKey).first<{target_type:string;target_id:string}>();
 if(previous)return executeAdminOperation(db,{actorPrincipalId:context.principalId,capability,action:'jobs.'+input.kind,authnContextSafeRef:context.authnContextSafeRef,requestId:context.requestId,reason:input.reason,idempotencyKey:input.idempotencyKey,targetType:input.kind==='restore'?previous.target_type:input.target,targetId:input.kind==='restore'?input.sourceJobId:'bounded-job',payload:input},{primary:{name:'replay-only',sql:'UPDATE admin_jobs SET status=status WHERE 0 AND {{admin_guard}}',bindings:[]},result:{jobId:'',count:0}});
 if(input.kind==='restore'){
  const source=await db.prepare("SELECT scope_json,actor_principal_id,result_expires_at,processed_count,cursor_json FROM admin_jobs WHERE id=? AND kind='cleanup' AND status IN ('succeeded','failed','cancelled') AND (processed_count>0 OR cursor_json IS NOT NULL)").bind(input.sourceJobId).first<{scope_json:string;actor_principal_id:string;result_expires_at:string;processed_count:number;cursor_json:string|null}>();
  if(!source||source.actor_principal_id!==context.principalId||Date.parse(source.result_expires_at)<=Date.now())throw new AdminOperationError('ADMIN_RECOVERY_UNAVAILABLE',409);
  const sourceScope=JSON.parse(source.scope_json) as Scope;
  const count=source.processed_count+(source.cursor_json&&JSON.parse(source.cursor_json).phase==='detached'?1:0);
  if(!count)throw new AdminOperationError('ADMIN_RECOVERY_UNAVAILABLE',409);
  scope={...sourceScope,ids:sourceScope.ids.slice(0,count),versions:sourceScope.versions?.slice(0,count),sourceJobId:input.sourceJobId};
 }else if(input.kind==='cleanup'){
  const preview=await previewAdminCleanup(db,{target:input.target,ids:input.ids});
  if(preview.previewVersion!==input.previewVersion)throw new AdminOperationError('ADMIN_VERSION_CONFLICT',409);
  scope={target:input.target,ids:input.ids,versions:preview.versions};
 }else scope={target:input.target,ids:input.ids};
 const id=crypto.randomUUID(),now=new Date().toISOString();
 return executeAdminOperation(db,{actorPrincipalId:context.principalId,capability,action:'jobs.'+input.kind,authnContextSafeRef:context.authnContextSafeRef,requestId:context.requestId,reason:input.reason,idempotencyKey:input.idempotencyKey,targetType:scope.target,targetId:input.kind==='restore'?input.sourceJobId:'bounded-job',payload:input}, {
  primary:{name:'create-job',sql:`INSERT INTO admin_jobs (id,operation_id,actor_principal_id,capability,kind,scope_json,status,next_attempt_at,created_at,updated_at,result_expires_at)
   SELECT ?,id,actor_principal_id,capability,?,?,'queued',?,?,?,? FROM admin_operations WHERE actor_principal_id=? AND idempotency_key=? AND status='pending' AND {{admin_guard}}`,bindings:[id,input.kind,JSON.stringify(scope),now,now,now,new Date(Date.now()+(input.kind==='export'?1:180)*86400000).toISOString(),context.principalId,input.idempotencyKey]},result:{jobId:id,count:scope.ids.length},
 });
}

type Job={id:string;operation_id:string;actor_principal_id:string;capability:string;kind:string;scope_json:string;processed_count:number;attempts:number;lease_token:string|null;status:string;result_expires_at:string;cursor_json:string|null};
const authority="EXISTS (SELECT 1 FROM admin_principals p WHERE p.id=admin_jobs.actor_principal_id AND p.status='active' AND EXISTS (SELECT 1 FROM json_each(p.capabilities_json) c WHERE c.value=admin_jobs.capability))";
const leaseGuard=`EXISTS (SELECT 1 FROM admin_jobs WHERE id=? AND lease_token=? AND status='running' AND julianday(lease_expires_at)>julianday('now') AND ${authority})`;
async function authorizedLease(db:AdminDatabase,id:string,lease:string){return !!await db.prepare(`SELECT id FROM admin_jobs WHERE id=? AND lease_token=? AND status='running' AND julianday(lease_expires_at)>julianday('now') AND ${authority}`).bind(id,lease).first();}

/** A fresh marker ties the mutation, audit and audit-presence assertion to this batch. */
export async function transitionAdminJob(db:AdminDatabase,id:string,action:string,set:string,values:unknown[],predicate:string,bounds:unknown[],keepLease=false){
 const marker=crypto.randomUUID(),audit=crypto.randomUUID(),now=new Date().toISOString();
 const statements=[db.prepare(`UPDATE admin_jobs SET ${set},lease_token=?,updated_at=? WHERE id=? AND (${predicate})`).bind(...values,marker,now,id,...bounds),
  db.prepare(`INSERT INTO admin_audit_events (id,operation_id,actor_principal_id,authn_context_safe_ref,capability,action,target_type,target_id,request_id,reason,result,error_code_safe,source_context_safe,created_at)
   SELECT ?,j.operation_id,j.actor_principal_id,'job:'||j.operation_id,j.capability,?,'admin-job',j.id,o.request_id,o.reason,
   CASE WHEN j.status='failed' THEN 'failed' WHEN j.status='cancelled' THEN 'denied' ELSE 'success' END,j.error_code_safe,'admin-job-worker',?
   FROM admin_jobs j JOIN admin_operations o ON o.id=j.operation_id WHERE j.id=? AND j.lease_token=?`).bind(audit,action,now,id,marker),
  db.prepare(`UPDATE admin_jobs SET status='audit-missing' WHERE id=? AND lease_token=? AND NOT EXISTS (SELECT 1 FROM admin_audit_events WHERE id=?)`).bind(id,marker,audit)];
 if(!keepLease)statements.push(db.prepare('UPDATE admin_jobs SET lease_token=NULL,lease_expires_at=NULL WHERE id=? AND lease_token=?').bind(id,marker));
 assertAdminBatchSucceeded(await db.batch(statements));return marker;
}
const transition=transitionAdminJob;
async function applyStep(db:AdminDatabase,job:Job,lease:string,scope:Scope,phase:string,primary:AdminGuardedStatement,effects:AdminGuardedStatement[]=[]){
 const original=await db.prepare('SELECT request_id,reason FROM admin_operations WHERE id=?').bind(job.operation_id).first<{request_id:string;reason:string}>();
 if(!original)throw new Error('ADMIN_JOB_OPERATION_MISSING');
 const result=await executeAdminOperation(db,{actorPrincipalId:job.actor_principal_id,capability:job.capability,action:`jobs.${job.kind}.${phase}`,authnContextSafeRef:'job:'+job.operation_id,requestId:original.request_id,reason:original.reason,idempotencyKey:`job:${job.id}:${job.processed_count}:${phase}`,targetType:scope.target,targetId:scope.ids[job.processed_count],payload:{jobId:job.id,index:job.processed_count,phase}}, {primary,effects,result:{index:job.processed_count,phase}});
 if(result.status==='conflict')throw new AdminOperationError('ADMIN_VERSION_CONFLICT',409);
}
function progressStatement(job:Job,lease:string,scope:Scope):AdminGuardedStatement{
 const now=new Date().toISOString();return {name:'progress',sql:`UPDATE admin_jobs SET processed_count=processed_count+1,cursor_json=NULL,status=?,attempts=0,error_code_safe=NULL,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=?,updated_at=? WHERE id=? AND lease_token=? AND ${authority} AND {{admin_guard}}`,bindings:[job.processed_count+1===scope.ids.length?'succeeded':'queued',now,now,job.id,lease],expectedChanges:1};
}
async function saveSnapshot(bucket:AdminPrivateBucket,key:string,text:string){
 const old=await bucket.get(key);if(old){if(await old.text()!==text)throw new AdminOperationError('ADMIN_RECOVERY_INVALID',409);return;}await bucket.put(key,text);
}
/** One bounded item per delivery. Detached objects have durable recovery state before any R2 delete. */
export async function runAdminJobStep(db:AdminDatabase,bucket:AdminPrivateBucket,id:string){
 const now=new Date().toISOString();
 await transition(db,id,'jobs.cancel','status=\'cancelled\',error_code_safe=\'ADMIN_PRINCIPAL_REVOKED\'',[],`status IN ('queued','running') AND NOT (${authority})`,[]);
 await transition(db,id,'jobs.exhausted',"status='failed',error_code_safe='ADMIN_JOB_ATTEMPTS_EXHAUSTED'",[],"attempts>=5 AND (status='queued' OR (status='running' AND julianday(lease_expires_at)<julianday('now')))",[]);
 const lease=await transition(db,id,'jobs.claim',"status='running',lease_expires_at=?,attempts=attempts+1",[new Date(Date.now()+60000).toISOString()],`(status='queued' OR (status='running' AND julianday(lease_expires_at)<julianday('now'))) AND julianday(next_attempt_at)<=julianday(?) AND attempts<5 AND ${authority}`,[now],true);
 const job=await db.prepare('SELECT id,operation_id,actor_principal_id,capability,kind,scope_json,processed_count,attempts,lease_token,status,result_expires_at,cursor_json FROM admin_jobs WHERE id=? AND lease_token=?').bind(id,lease).first<Job>();
 if(!job)return;
 try{
  const scope=JSON.parse(job.scope_json) as Scope,index=job.processed_count,targetId=scope.ids[index];
  if(!targetId||scope.ids.length>100||Date.parse(job.result_expires_at)<=Date.now())throw new AdminOperationError('ADMIN_JOB_SCOPE_EXPIRED',409);
  const prefix=`admin/${job.kind==='export'?'exports':'recovery'}/${id}/${index}`;
  if(job.kind==='export'){
   const data=await readAdminResource(db,exportTargets.parse(scope.target),{id:targetId,limit:1});
   if(!data.items.length)throw new AdminOperationError('ADMIN_EXPORT_TARGET_MISSING',409);
   if(!await authorizedLease(db,id,lease))return;
   const advance=progressStatement(job,lease,scope);
   if(scope.target==='generations'){
    const body=await db.prepare(`SELECT r2_key,content_encoding,updated_at FROM large_objects WHERE kind='battle_report_generation_output' AND owner_ref_id=? AND EXISTS (SELECT 1 FROM battle_report_generations g WHERE g.id=owner_ref_id AND ${terminalGeneration('g')}) ORDER BY created_at DESC LIMIT 1`).bind(targetId).first<{r2_key:string;content_encoding:string|null;updated_at:string}>();
    if(!body)throw new AdminOperationError('ADMIN_EXPORT_BODY_UNAVAILABLE',409);
    const object=await bucket.get(body.r2_key);if(!object)throw new AdminOperationError('ADMIN_EXPORT_BODY_UNAVAILABLE',409);
    if(body.content_encoding&&body.content_encoding!=='gzip')throw new AdminOperationError('ADMIN_EXPORT_ENCODING_UNSUPPORTED',409);
    const decompressor=new DecompressionStream('gzip') as unknown as {readable:ReadableStream<Uint8Array>;writable:WritableStream<Uint8Array>};
    await bucket.put(prefix+'.body',body.content_encoding==='gzip'?object.body.pipeThrough(decompressor):object.body);
    data.items[0].bodyPart=index;
    advance.sql=advance.sql.replace('AND {{admin_guard}}',`AND EXISTS (SELECT 1 FROM large_objects o JOIN battle_report_generations g ON g.id=o.owner_ref_id WHERE o.owner_ref_id=? AND o.kind='battle_report_generation_output' AND o.r2_key=? AND o.updated_at=? AND g.updated_at=? AND ${terminalGeneration('g')}) AND {{admin_guard}}`);
    advance.bindings=[...advance.bindings,targetId,body.r2_key,body.updated_at,data.items[0].updated_at];
   }
   await bucket.put(prefix+'.json',JSON.stringify(data.items[0]));
   await applyStep(db,job,lease,scope,'export',advance);return;
  }
  const target=targetSchema.parse(scope.target),names=columns(target);
  if(job.kind==='restore'){
   const saved=await bucket.get(`admin/recovery/${scope.sourceJobId}/${index}.json`);if(!saved)throw new AdminOperationError('ADMIN_RECOVERY_UNAVAILABLE',409);
   const row=JSON.parse(await saved.text()) as Record<string,unknown>;
   if(await digest(row)!==scope.versions?.[index])throw new AdminOperationError('ADMIN_RECOVERY_INVALID',409);
   if(!await authorizedLease(db,id,lease))return;
   if(target==='large_objects'){
    const body=await bucket.get(`admin/recovery/${scope.sourceJobId}/${index}.body`);if(!body)throw new AdminOperationError('ADMIN_RECOVERY_UNAVAILABLE',409);
    // A fresh namespace cannot collide with the retired original key or another recovery job.
    row.r2_key=`recovered/admin/${id}/${index}`;
    if(!await bucket.get(String(row.r2_key)))await bucket.put(String(row.r2_key),body.body);
   }
   await applyStep(db,job,lease,scope,'restore',{name:'restore',sql:`INSERT INTO ${target} (${names.join(',')}) SELECT ${names.map(()=>'?').join(',')} WHERE NOT EXISTS (SELECT 1 FROM ${target} WHERE ${definitions[target].key}=?) AND ${leaseGuard} AND {{admin_guard}}`,bindings:[...names.map(n=>row[n]??null),targetId,id,lease]},[progressStatement(job,lease,scope)]);return;
  }
  if(job.kind!=='cleanup')throw new AdminOperationError('ADMIN_JOB_KIND_INVALID',409);
  const cursor=job.cursor_json?JSON.parse(job.cursor_json) as {phase:string;r2Key:string}:null;
  if(target==='large_objects'&&cursor?.phase==='detached'){
   if(!await authorizedLease(db,id,lease))return;
   const tombstone=await db.prepare('SELECT r2_key FROM admin_object_tombstones WHERE r2_key=? AND job_id=? AND large_object_id=?').bind(cursor.r2Key,id,targetId).first();
   if(!tombstone)throw new AdminOperationError('ADMIN_RECOVERY_INVALID',409);
   await bucket.delete(cursor.r2Key);
   await applyStep(db,job,lease,scope,'delete-object',progressStatement(job,lease,scope));return;
  }
  const row=await cleanupRow(db,target,targetId);
  if(!row||await digest(row)!==scope.versions?.[index])throw new AdminOperationError('ADMIN_VERSION_CONFLICT',409);
  if(!await authorizedLease(db,id,lease))return;
  await saveSnapshot(bucket,prefix+'.json',JSON.stringify(row));
  const primary:AdminGuardedStatement={name:'detach',sql:`DELETE FROM ${target} WHERE ${definitions[target].key}=? AND ${eligible(target)} AND ${names.map(n=>`${n} IS ?`).join(' AND ')} AND ${leaseGuard} AND {{admin_guard}}`,bindings:[targetId,...names.map(n=>row[n]??null),id,lease]};
  if(target==='large_objects'){
   if(!await bucket.get(prefix+'.body')){const original=await bucket.get(String(row.r2_key));if(!original)throw new AdminOperationError('ADMIN_RECOVERY_SOURCE_MISSING',409);await bucket.put(prefix+'.body',original.body);}
   await applyStep(db,job,lease,scope,'detach',primary,[
    {name:'tombstone',sql:'INSERT INTO admin_object_tombstones (r2_key,job_id,large_object_id,created_at) SELECT ?,?,?,? WHERE {{admin_guard}}',bindings:[row.r2_key,id,targetId,now],expectedChanges:1},
    {name:'detached-progress',sql:`UPDATE admin_jobs SET cursor_json=?,status='queued',attempts=0,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=?,updated_at=? WHERE id=? AND lease_token=? AND ${authority} AND {{admin_guard}}`,bindings:[JSON.stringify({phase:'detached',r2Key:row.r2_key}),now,now,id,lease],expectedChanges:1},
   ]);return;
  }
  await applyStep(db,job,lease,scope,'cleanup',primary,[progressStatement(job,lease,scope)]);
 }catch(error){
  await transition(db,id,'jobs.failure','status=?,error_code_safe=?,next_attempt_at=?',[error instanceof AdminOperationError||job.attempts>=5?'failed':'queued',error instanceof AdminOperationError?error.code:'ADMIN_JOB_RETRYABLE',new Date(Date.now()+60000).toISOString()],'lease_token=?',[lease]);
 }
}
export async function readAdminJobs(db:AdminDatabase,principalId:string){
 const result=await db.prepare(`SELECT id,kind,status,processed_count,attempts,error_code_safe,result_expires_at,created_at,updated_at,
  json_extract(scope_json,'$.target') AS target,coalesce(json_array_length(scope_json,'$.ids'),json_array_length(scope_json,'$.targets')) AS total_count,
  json_extract(cursor_json,'$.model') AS model,json_extract(cursor_json,'$.usage') AS usage,
  processed_count+CASE WHEN json_extract(cursor_json,'$.phase')='detached' THEN 1 ELSE 0 END AS recoverable_count
  FROM admin_jobs WHERE actor_principal_id=? AND ${authority} ORDER BY created_at DESC LIMIT 100`).bind(principalId).all();
 if(!result.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');return result.results;
}
export async function cancelAdminJob(db:AdminDatabase,raw:unknown,context:AdminActionContext){
 const input=z.object({...commonInput,id:z.string().uuid(),expectedUpdatedAt:z.string().min(1).max(128)}).strict().parse(raw);
 return executeAdminOperation(db,{actorPrincipalId:context.principalId,capability:'data.maintenance',action:'jobs.cancel',authnContextSafeRef:context.authnContextSafeRef,requestId:context.requestId,reason:input.reason,idempotencyKey:input.idempotencyKey,expectedVersion:input.expectedUpdatedAt,targetType:'admin-job',targetId:input.id,payload:input},{
  primary:{name:'cancel-job',sql:`UPDATE admin_jobs SET status='cancelled',lease_token=NULL,lease_expires_at=NULL,error_code_safe='ADMIN_OPERATOR_CANCELLED',updated_at=? WHERE id=? AND actor_principal_id=? AND updated_at=? AND status IN ('queued','running','uncertain') AND ${authority} AND {{admin_guard}}`,bindings:[new Date().toISOString(),input.id,context.principalId,input.expectedUpdatedAt]},result:{jobId:input.id,status:'cancelled'},
 });
}
async function exportObject(db:AdminDatabase,bucket:AdminPrivateBucket,principalId:string,id:string,part:number,extension:'json'|'body'){
 if(!Number.isSafeInteger(part)||part<0||part>=100||!z.string().uuid().safeParse(id).success)throw new AdminOperationError('ADMIN_EXPORT_INVALID',400);
 const job=await db.prepare(`SELECT id FROM admin_jobs WHERE id=? AND actor_principal_id=? AND kind='export' AND status='succeeded' AND processed_count>? AND julianday(result_expires_at)>julianday('now') AND ${authority}`).bind(id,principalId,part).first();
 if(!job)throw new AdminOperationError('ADMIN_EXPORT_UNAVAILABLE',403);
 const object=await bucket.get(`admin/exports/${id}/${part}.${extension}`);if(!object)throw new AdminOperationError('ADMIN_EXPORT_UNAVAILABLE',404);return object;
}
export const downloadAdminExport=(db:AdminDatabase,bucket:AdminPrivateBucket,principalId:string,id:string,part:number)=>exportObject(db,bucket,principalId,id,part,'json');
export const downloadAdminExportBody=(db:AdminDatabase,bucket:AdminPrivateBucket,principalId:string,id:string,part:number)=>exportObject(db,bucket,principalId,id,part,'body');
export async function scanAdminJobs(db:AdminDatabase){
 const rows=await db.prepare("SELECT id FROM admin_jobs WHERE (status='queued' OR (status='running' AND julianday(lease_expires_at)<julianday('now'))) AND julianday(next_attempt_at)<=julianday('now') ORDER BY next_attempt_at LIMIT 20").all<{id:string}>();
 if(!rows.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');return rows.results;
}

/** A retired/staged key may still belong to a live row or an in-flight cleanup/recovery chain. */
async function objectHasLiveReference(db:AdminDatabase,key:string){
 return !!await db.prepare(`SELECT 1 AS present FROM large_objects WHERE r2_key=?
  UNION ALL SELECT 1 FROM admin_object_tombstones t JOIN admin_jobs j
   ON j.id=t.job_id OR json_extract(j.scope_json,'$.sourceJobId')=t.job_id
   WHERE t.r2_key=? AND j.status IN ('queued','running','uncertain') LIMIT 1`).bind(key,key).first();
}

/** Fixed, bounded scheduler maintenance. No business-panel input and no active-job audit deletion. */
export async function expireAdminArtifacts(db:AdminDatabase,bucket:AdminPrivateBucket){
 const jobs=await db.prepare("SELECT id,scope_json,cursor_json FROM admin_jobs WHERE kind='export' AND status IN ('succeeded','failed','cancelled') AND julianday(result_expires_at)<=julianday('now') AND coalesce(json_extract(cursor_json,'$.expired'),0)=0 ORDER BY result_expires_at LIMIT 5").all<{id:string;scope_json:string;cursor_json:string|null}>();
 if(!jobs.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');
 for(const job of jobs.results){
  const scope=JSON.parse(job.scope_json) as Scope,cursor=job.cursor_json?JSON.parse(job.cursor_json) as {expiryIndex?:number}:{};
  const index=cursor.expiryIndex??0;
  await bucket.delete(`admin/exports/${job.id}/${index}.json`);await bucket.delete(`admin/exports/${job.id}/${index}.body`);
  await transition(db,job.id,'jobs.expire-export','cursor_json=?',[JSON.stringify(index+1>=scope.ids.length?{expired:true}:{expiryIndex:index+1})],"kind='export' AND status IN ('succeeded','failed','cancelled') AND cursor_json IS ?",[job.cursor_json]);
 }
 const aiJobs=await db.prepare("SELECT id FROM admin_jobs WHERE kind='ai-review' AND status IN ('succeeded','failed','cancelled') AND julianday(result_expires_at)<=julianday('now') AND coalesce(json_extract(cursor_json,'$.resultExpired'),0)=0 ORDER BY result_expires_at LIMIT 5").all<{id:string}>();
 if(!aiJobs.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');
 for(const job of aiJobs.results){
  await bucket.delete(`admin/ai-results/${job.id}.json`);
  await transition(db,job.id,'jobs.expire-ai-result',"result_ref=NULL,cursor_json=json_set(coalesce(cursor_json,'{}'),'$.resultExpired',1)",[],"kind='ai-review' AND status IN ('succeeded','failed','cancelled') AND julianday(result_expires_at)<=julianday('now') AND coalesce(json_extract(cursor_json,'$.resultExpired'),0)=0",[]);
 }
 const recoveryJobs=await db.prepare("SELECT id,scope_json,cursor_json FROM admin_jobs WHERE kind='cleanup' AND status IN ('succeeded','failed','cancelled') AND julianday(result_expires_at)<=julianday('now') AND coalesce(json_extract(cursor_json,'$.recoveryExpired'),0)=0 AND NOT EXISTS (SELECT 1 FROM admin_jobs recovering WHERE recovering.kind='restore' AND json_extract(recovering.scope_json,'$.sourceJobId')=admin_jobs.id AND recovering.status IN ('queued','running','uncertain')) ORDER BY result_expires_at LIMIT 5").all<{id:string;scope_json:string;cursor_json:string|null}>();
 if(!recoveryJobs.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');
 for(const job of recoveryJobs.results){
  const scope=JSON.parse(job.scope_json) as Scope,cursor=job.cursor_json?JSON.parse(job.cursor_json) as {recoveryExpiryIndex?:number}:{};
  const index=cursor.recoveryExpiryIndex??0;
  // Cancelled/exhausted detached jobs never revisit the normal delete step. Their old key remains fenced by its tombstone.
  const retired=await db.prepare('SELECT r2_key FROM admin_object_tombstones WHERE job_id=? AND large_object_id=?').bind(job.id,scope.ids[index]).first<{r2_key:string}>();
  if(retired){
   if(await objectHasLiveReference(db,retired.r2_key))continue;
   await bucket.delete(retired.r2_key);
  }
  await bucket.delete(`admin/recovery/${job.id}/${index}.json`);await bucket.delete(`admin/recovery/${job.id}/${index}.body`);
  await transition(db,job.id,'jobs.expire-recovery',"cursor_json=json_set(coalesce(cursor_json,'{}'),'$.recoveryExpiryIndex',?,'$.recoveryExpired',?)",[index+1,index+1>=scope.ids.length?1:0],"kind='cleanup' AND status IN ('succeeded','failed','cancelled') AND cursor_json IS ?",[job.cursor_json]);
 }
 // Restore uploads precede the guarded D1 insert. Failed/cancelled restores can therefore leave an unreferenced staged body.
 const restores=await db.prepare("SELECT id,scope_json,cursor_json FROM admin_jobs WHERE kind='restore' AND status IN ('failed','cancelled') AND json_extract(scope_json,'$.target')='large_objects' AND julianday(result_expires_at)<=julianday('now') AND coalesce(json_extract(cursor_json,'$.orphansExpired'),0)=0 ORDER BY result_expires_at LIMIT 5").all<{id:string;scope_json:string;cursor_json:string|null}>();
 if(!restores.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');
 for(const job of restores.results){
  const scope=JSON.parse(job.scope_json) as Scope,cursor=job.cursor_json?JSON.parse(job.cursor_json) as {orphanExpiryIndex?:number}:{};
  const index=cursor.orphanExpiryIndex??0,key=`recovered/admin/${job.id}/${index}`;
  // Referenced bodies remain business data. Their eventual retirement belongs to the referencing cleanup job.
  if(!await objectHasLiveReference(db,key))await bucket.delete(key);
  await transition(db,job.id,'jobs.expire-restore-orphan',"cursor_json=json_set(coalesce(cursor_json,'{}'),'$.orphanExpiryIndex',?,'$.orphansExpired',?)",[index+1,index+1>=scope.ids.length?1:0],"kind='restore' AND status IN ('failed','cancelled') AND cursor_json IS ?",[job.cursor_json]);
 }
 const result=await db.prepare("DELETE FROM admin_audit_events WHERE id IN (SELECT a.id FROM admin_audit_events a WHERE julianday(a.created_at)<julianday('now','-180 days') AND NOT EXISTS (SELECT 1 FROM admin_jobs j WHERE (j.operation_id=a.operation_id OR j.id=a.target_id OR EXISTS (SELECT 1 FROM admin_operations step WHERE step.id=a.operation_id AND substr(step.idempotency_key,1,length(j.id)+5)='job:'||j.id||':') OR EXISTS (SELECT 1 FROM admin_jobs source WHERE source.id=json_extract(j.scope_json,'$.sourceJobId') AND (source.operation_id=a.operation_id OR source.id=a.target_id OR EXISTS (SELECT 1 FROM admin_operations step WHERE step.id=a.operation_id AND substr(step.idempotency_key,1,length(source.id)+5)='job:'||source.id||':')))) AND j.status IN ('queued','running','uncertain')) ORDER BY a.created_at LIMIT 100)").run();
 if(!result.success)throw new Error('ADMIN_DATABASE_UNAVAILABLE');return {exportsVisited:jobs.results.length,aiResultsVisited:aiJobs.results.length,recoveryVisited:recoveryJobs.results.length,restoreOrphansVisited:restores.results.length,auditsRemoved:result.meta?.changes??0};
}
